Revised 'introduction to relational databases' outline #1202
Techtonica/curriculum pull request #1396
Opened 2020-09-15 13:47 UTC by iamdhruvsharma

I made the required changes as per the instructions. Please have a look and do let me know if any other addition/deletion is required.

2020-09-21 16:07 UTC, alodahl commented
Hi @iamdhruvsharma , I'm visiting relatives this week so I haven't had a chance to look at this, but I haven't forgotten =)

2020-09-21 16:44 UTC, iamdhruvsharma commented
> Hi @iamdhruvsharma , I'm visiting relatives this week so I haven't had a chance to look at this, but I haven't forgotten =)

No, issues! :) 
Do let me know, if any more changes are required.

2020-09-26 21:56 UTC, alodahl commented
@iamdhruvsharma would you be able to resolve the conflicts?

2020-09-26 22:15 UTC, alodahl commented
Hi @vegetabill , would you mind taking a look at the SQL syntax?  I'm going to proofread and check-off that tasks were addressed, but I'm barely familiar with SQL.

2020-09-28 07:24 UTC, iamdhruvsharma commented
> @iamdhruvsharma would you be able to resolve the conflicts?

Yes. I believe but I suggest you to please have a look yourself and let me know if any further changes are required.

2020-09-30 16:25 UTC, alodahl requested changes
Hi @iamdhruvsharma 

Thanks for taking this on.  

- Regarding the first AC, “make guided practice more guided”, this is a section where apprentices will be experiencing these commands for the very first time, so it needs to be _concrete_.  Rather than saying “Go ahead and make a select request”,it should be more like, “Spend up to x minutes/  following the tutorial at this link until you get to <a certain point>”, or “First, run this exact command: `command`.  The purpose of the command is <this>. You should expect to see <this output>.  Next, do this exact command: `command`… etc.”  

- Also, be aware that this is not actually the first SQL lesson, but it is the first regarding related tables.  Exercises should only focus on this skill. Here is the lesson in context with what apprentices will study that week: https://github.com/Techtonica/curriculum#week-7---databases

- I think that the last AC about *replacing example commands with real guided activity on how to manipulate a table* refers to the “Relational Database basics” section.  The ask is to have this be interactive, rather than a passive list of examples.  Feel free to use what is there, combine it with the first AC I mentioned above… the goal is to explain basic relational database tasks *and* give apprentices some experience with the process at the same time. Turning it into steps for apprentices to follow could work.

- What is “IMP”?

2020-10-06 09:51 UTC, iamdhruvsharma commented
> Hi @iamdhruvsharma
> 
> Thanks for taking this on.
> 
> * Regarding the first AC, “make guided practice more guided”, this is a section where apprentices will be experiencing these commands for the very first time, so it needs to be _concrete_.  Rather than saying “Go ahead and make a select request”,it should be more like, “Spend up to x minutes/  following the tutorial at this link until you get to ”, or “First, run this exact command: `command`.  The purpose of the command is . You should expect to see .  Next, do this exact command: `command`… etc.”
> * Also, be aware that this is not actually the first SQL lesson, but it is the first regarding related tables.  Exercises should only focus on this skill. Here is the lesson in context with what apprentices will study that week: https://github.com/Techtonica/curriculum#week-7---databases
> * I think that the last AC about _replacing example commands with real guided activity on how to manipulate a table_ refers to the “Relational Database basics” section.  The ask is to have this be interactive, rather than a passive list of examples.  Feel free to use what is there, combine it with the first AC I mentioned above… the goal is to explain basic relational database tasks _and_ give apprentices some experience with the process at the same time. Turning it into steps for apprentices to follow could work.
> * What is “IMP”?


Thanks for the clarification, on it now. IMP - IMPORTANT. :)

2020-10-25 21:33 UTC, alodahl commented on databases/relational-databases.md
> +  - Storgae of information
Storage?

2020-10-25 21:34 UTC, alodahl commented
Can you please change "IMP" to important, then?  Let me know when you've had time to address the comments.

2020-10-31 18:27 UTC, alodahl commented
Hi @iamdhruvsharma , will you be able to make the requested fixes soon?

2020-11-08 20:28 UTC, alodahl commented
Hi @iamdhruvsharma , are you still able to work in this?

2020-11-09 09:17 UTC, iamdhruvsharma commented
> Hi @iamdhruvsharma , are you still able to work in this?

Hi There!

Sorry for late reply, I was extremely busy with my exams and preparation but now I am available and will complete this request as soon as possible.

Thank you for your patience.

2020-11-09 09:24 UTC, iamdhruvsharma commented on databases/relational-databases.md
> +  - Storgae of information
Yeah! I will correct it.

2020-11-09 15:22 UTC, alodahl commented
Thanks! It would also be helpful if the commit messages were descriptive of the changes.

2020-11-28 05:21 UTC, vegetabill requested changes
Looking pretty good so far. If you add in the guided practice and polish up a few of these other areas, it'll be in great shape. Thanks!

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +- [Few basic column data types](https://www.w3schools.com/sql/sql_datatypes.asp)
Please link to commonly used postgres data types

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +  - `varchar` (Just like **string** available in different programming languages like JS)
Can you add the comparison with JS for all to the data types that apply? The issue just mentioned this one as an example.

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +  - `primary key`
It's a little confusing to have PK in the same list of data types, as they are different concepts.

I would split it into a separate section explaining what a primary key is, that it must be unique and can be different types but is commonly an auto-increment integer.

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +  - `boolean or bool` (For storing true, false or null)
Just use `boolean` as that's what Postgres calls it.

(Also every type can be `null` if the column allows it so I don't think it makes sense to say that specifically here)

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +  - `int` (For holding Numeric Values)
Postgres refers to this as `integer`

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +    - The SELECT statement is used to select/retrieve data from a database.
Let's say `read rows` instead of `select/retrieve data`

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +- Different types of [non-relational databases](https://medium.com/@mark.rethana/introduction-to-nosql-databases-c5b43f3ca1cc) (non-sql databases):
Can you make this just normal text, not a bullet point and then un-indent the rest so it's just one-level list instead of two-level?

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
> +- A database can be referred to as a table or collection of tables, a database server, or SQL. You have to consider the context for better understanding.
Can you clarify at the beginning of the sentence: 

> The term "database" can be...

2020-11-28 05:21 UTC, vegetabill commented on databases/relational-databases.md
>  - Go through the course [Databases Course: Querying Relational Databases (145 min)](https://teamtreehouse.com/library/querying-relational-databases). In this course the concepts of Set Theory and Dat
One of the big asks of the issue was to make the guided practice guided with step-by-step instructions and it's mostly unchanged here. Can you fill in how to do each step? Feel free to pick some example data to illustrate the concepts such as an animals or pets table, or something else less dry than the usual customer examples of the SQL world.

2020-12-30 21:59 UTC, alodahl commented
@vegetabill do you think it would be productive to merge this and have it "address" rather than solve the issue, or does it introduce new complications?

2020-12-31 06:37 UTC, vegetabill commented
@alodahl yeah let's take the work in progress and revise the issue. I'll fix a few of the small items and then merge, leaving the issue to be to work on the guided practice.

2020-12-31 06:46 UTC, vegetabill commented
@iamdhruvsharma you made this PR from your master branch which doesn't really make sense. Closing this.

2020-12-31 06:46 UTC, closed without merging