[Eventonica] Revise (and reorder) Part 3 - React
Techtonica/curriculum pull request #1472
Opened 2021-02-13 02:29 UTC by vegetabill

Resolves #1421 

  - Fill in Eventonica Part 3 lesson with step-by-step examples of porting a JS DOM app to React
  - This should be rebased against #1471 first
  - Sample code adapted from @lisaau https://github.com/lisaau/Eventonica/blob/master/src/jQuery-scripts.js

2021-02-22 00:18 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +Now, however, we want the UI to re-render when we delete the user. There is not one best way to do this so you'll have to use the lessons you learned previously to figure out how to accomplish this f
Isn't the best way to update the state?

2021-02-22 00:31 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +Now, however, we want the UI to re-render when we delete the user. There is not one best way to do this so you'll have to use the lessons you learned previously to figure out how to accomplish this f
updating the state should always cause a re-render.

2021-02-22 00:35 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +Here is example code that might be simmilar to the way you displayed a list of users in your app. Depending on how to built Part 2, your code might not be in a function like this but hopefully you ca
```suggestion
Here is example code that might be similar to the way you displayed a list of users in your app. Depending on how you built Part 2, your code might not be in a function like this, but hopefully you can translate the concept to your own design.
```

2021-02-22 00:45 UTC, alodahl requested changes
Looks good, I'm just concerned about the class name, and about the re-render comment at the end.  Re-rendering on state change is like the main point of React.

2021-02-22 00:45 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +const eventRecommender = new EventRecommender();
isn't this class called Eventonica now?

2021-02-22 00:45 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +        <UsersList users={eventRecommender.users} />
eventonica

2021-02-22 00:45 UTC, alodahl commented on projects/eventonica/eventonica-part7-react.md
> +        <UsersList users={eventRecommender.users} />
theres a few more spots, too

2021-02-27 22:01 UTC, vegetabill commented
Thanks for reviewing! Since I have a little cushion of time on this, going to prioritize cleaning up the whole Eventonica mess and will come back to this in a week or so.

2021-03-01 18:48 UTC, closed without merging

2021-03-01 18:53 UTC, vegetabill commented
@alodahl oof I did something dumb with git and now it thinks this is closed.

The real changes are now in #1505  including all your suggested revisions.