Added clear project requirements for week 8 game.
Techtonica/curriculum pull request #2098
Opened 2024-10-29 17:45 UTC by Lakhwinderr

Added new project requirements for users to customize the trivia game by selecting the number of questions, question type, difficulty, and category.

2024-10-29 18:06 UTC, daaimah123 requested changes

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +   - Create initial components: GameSetup, GamePlay, and GameResult.
```suggestion
   - Create initial components such as `GameSetup`, `GamePlay`, and `GameResult`.
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +The game's existing code already includes functionality to fetch user information and display questions from the `fakedata.js` file. Your task will be to replace this with real API data and implement
```suggestion
The game's existing code already includes functionality to fetch user information and display questions from the `fakedata.js` file. Your task will be to replace this with real API data and implement additional features. See [example game code](https://github.com/Yosolita1978/week8Game).
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +1. **API Request Setup**:
```suggestion
- [ ] **API Request Setup**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +1. **Game Setup Screen**:
```suggestion
- [ ] **Game Setup Screen**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +2. **Game Interface**:
```suggestion
- [ ] **Game Interface**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +3. **Result Display**:
```suggestion
- [ ] **Result Display**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +1. **Frontend Initialization**:
```suggestion
- [ ] **Frontend Initialization**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +2. **Backend Initialization**:
```suggestion
- [ ] **Backend Initialization**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +3. **Frontend-Backend Integration**:
```suggestion
- [ ] **Frontend-Backend Integration**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +4. **Win/Loss Logic**:
```suggestion
- [ ] **Win/Loss Logic**:
```

2024-10-29 18:06 UTC, daaimah123 commented on projects/week8GameREADME.md
> +5. **Testing and Debugging**:
```suggestion
- [ ] **Bonus Feature: Testing and Debugging**:
```

2024-10-29 19:15 UTC, merged

2024-10-29 19:33 UTC, Lakhwinderr commented
Thanks 😊 @daaimah123

2024-10-31 00:35 UTC, daaimah123 commented
@Lakhwinderr "hacktoberfest-accepted"