Resolving Issue #2158 - Standardizing Link Names in Supplemental Materials Section
Techtonica/curriculum pull request #2195
Opened 2024-12-29 18:25 UTC by ChasVanDav

## Overview  
This pull request addresses [Issue #2158](https://github.com/Techtonica/curriculum/issues/2158) by updating the links in the **Supplemental Materials** section of the open-source curriculum. The updates standardize the naming conventions for the links, improving consistency and usability.

## What Was Done  

1. **Link Updates:**  
   - Revised all links in the **Supplemental Materials** section to follow a consistent format:  
   - Include the name of the list.   
   - Display the creator/maintainer of the resource.  
    - Indicate any filters applied by the specific link.  

2. **Consistency Improvements:**  
   - Improved readability and navigability of the list by applying a uniform naming structure.  

3. **Post-PR #2153 Adjustments:**  
   - Incorporated changes on top of the revised list structure introduced in PR #2153, ensuring compatibility with the updated content.

## Status  
This pull request is ready for review.

2024-12-29 18:27 UTC, ChasVanDav commented
@daaimah123 @thisIsTheWei I have addressed issue 2158 by updating link names as requested. Please review and let me know your thoughts!

2024-12-29 18:32 UTC, daaimah123 requested changes

2024-12-29 18:32 UTC, daaimah123 commented on open-source/open-source.md
> +MunGell), Filter Applied: None](https://github.com/MunGell/awesome-for-beginners#javascript)
```suggestion
MunGell), Filter Applied: JavaScript](https://github.com/MunGell/awesome-for-beginners#javascript)
```

2024-12-29 18:32 UTC, daaimah123 commented on open-source/open-source.md
> +- [Github First Contributions Homepage (Maintained by: Github), Filter Applied: None](https://roshanjossey.github.io/first-contributions/#project-list)
```suggestion
- [Github First Contributions Homepage (Maintained by: Github), Filter Applied: project-list](https://roshanjossey.github.io/first-contributions/#project-list)
```

2024-12-29 22:19 UTC, ChasVanDav commented on open-source/open-source.md
> +MunGell), Filter Applied: None](https://github.com/MunGell/awesome-for-beginners#javascript)
done!

2024-12-29 22:19 UTC, ChasVanDav commented on open-source/open-source.md
> +- [Github First Contributions Homepage (Maintained by: Github), Filter Applied: None](https://roshanjossey.github.io/first-contributions/#project-list)
done

2024-12-29 22:20 UTC, ChasVanDav commented
@daaimah123 I have updated both review changes and resolved the comments. If it looks good now, I will have @thisIsTheWei and a peer give it a final look. Thank you!

2024-12-30 19:01 UTC, thisIsTheWei approved these changes

2024-12-30 19:34 UTC, ChasVanDav commented
@stmcpeters Hi Steph! Would you give this pr a final look before we merge and close?

2024-12-30 19:43 UTC, stmcpeters commented
great work with the updated links and your PR is detailed, including all your changes. LGTM! 🥳

2024-12-30 19:44 UTC, stmcpeters approved these changes
great work with the updated links and your PR is detailed, including all your changes. LGTM! 🥳

2024-12-30 19:50 UTC, ChasVanDav commented
@daaimah123 All reviewers have approved this pr! I will merge this pr and close the issue!

2024-12-30 19:50 UTC, merged